#include "Ast.h"
#include "SymbolTable.h"
#include "Unit.h"
#include "Instruction.h"
#include "IRBuilder.h"
#include <string>
#include "Type.h"

extern Unit unit;
extern FILE *yyout;
int Node::counter = 0;
IRBuilder* Node::builder = nullptr;

Node::Node()
{
    seq = counter++;
    bro = nullptr;
}

Node* Node::getRightestBro(){
    Node* node = this;
    while(node->brother()){
        node = node->brother();
    }
    return node;
}

int BinaryExpr::intValue() {
    int value = 0;
    switch (op) {
        case ADD:
            value = expr1->intValue() + expr2->intValue();
            break;
        case SUB:
            value = expr1->intValue() - expr2->intValue();
            break;
        case MUL:
            value = expr1->intValue() * expr2->intValue();
            break;
        case DIV:
            value = expr1->intValue() / expr2->intValue();
            break;
        case MOD:
            value = expr1->intValue() % expr2->intValue();
            break;
        case AND:
            value = expr1->intValue() && expr2->intValue();
            break;
        case OR:
            value = expr1->intValue() || expr2->intValue();
            break;
        case LESS:
            value = expr1->intValue() < expr2->intValue();
            break;
        case LEQU:
            value = expr1->intValue() <= expr2->intValue();
            break;
        case GREAT:
            value = expr1->intValue() > expr2->intValue();
            break;
        case GEQU:
            value = expr1->intValue() >= expr2->intValue();
            break;
        case EQUAL:
            value = expr1->intValue() == expr2->intValue();
            break;
        case NOTEQUAL:
            value = expr1->intValue() != expr2->intValue();
            break;
        default:
            value = 0;
    }
    return value;
}
int UnaryExpr::intValue() {
        int value = 0;
    switch (op) {
        case SUB:
            value = -(expr->intValue());
            break;
        case NOT:
            value = !(expr->intValue());
            break;
        default:
            value = 0;
    }
    return value;
}
int Constant::intValue() {
    return ((ConstantSymbolEntry*)symbolEntry)->getValue();
}
int Id::intValue() {
    return ((IdentifierSymbolEntry*)symbolEntry)->getValue();
}

void Ast::output()
{
    fprintf(yyout, "program\n");
    if(root != nullptr)
        root->output(4);
}

void Node::backPatch(std::vector<Instruction*> &list, BasicBlock*bb)
{
    for(auto &inst:list)
    {
        if(inst->isCond())
            dynamic_cast<CondBrInstruction*>(inst)->setTrueBranch(bb);
        else if(inst->isUncond())
            dynamic_cast<UncondBrInstruction*>(inst)->setBranch(bb);
    }
}

std::vector<Instruction*> Node::merge(std::vector<Instruction*> &list1, std::vector<Instruction*> &list2)
{
    std::vector<Instruction*> res(list1);
    res.insert(res.end(), list2.begin(), list2.end());
    return res;
}

void Ast::genCode(Unit *unit)
{
    IRBuilder *builder = new IRBuilder(unit);
    Node::setIRBuilder(builder);
    root->genCode();
}

void FunctionDef::genCode()
{
    Unit *unit = builder->getUnit();
    Function *func = new Function(unit, se);
    BasicBlock *entry = func->getEntry();
    // set the insert point to the entry basicblock of this function.
    builder->setInsertBB(entry);

    stmt->genCode();

    /**
     * Construct control flow graph. You need do set successors and predecessors for each basic block.
     * Todo
    */
   
}

void BinaryExpr::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    Function *func = bb->getParent();
    if (op == AND)
    {
        BasicBlock *trueBB = new BasicBlock(func);  // if the result of lhs is true, jump to the trueBB.
        expr1->genCode();
        backPatch(expr1->trueList(), trueBB);
        builder->setInsertBB(trueBB);               // set the insert point to the trueBB so that intructions generated by expr2 will be inserted into it.
        expr2->genCode();
        true_list = expr2->trueList();
        false_list = merge(expr1->falseList(), expr2->falseList());
    }
    else if(op == OR)
    {
        // Todo
    }
    else if(op >= LESS && op <= GREAT)
    {
        // Todo
    }
    else if(op >= ADD && op <= SUB)
    {
        expr1->genCode();
        expr2->genCode();
        Operand *src1 = expr1->getOperand();
        Operand *src2 = expr2->getOperand();
        int opcode;
        switch (op)
        {
        case ADD:
            opcode = BinaryInstruction::ADD;
            break;
        case SUB:
            opcode = BinaryInstruction::SUB;
            break;
        }
        new BinaryInstruction(opcode, dst, src1, src2, bb);
    }
}

void Constant::genCode()
{
    // we don't need to generate code.
}

void Id::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getAddr();
    new LoadInstruction(dst, addr, bb);
}

void IfStmt::genCode()
{
    Function *func;
    BasicBlock *then_bb, *end_bb;

    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);

    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatch(cond->falseList(), end_bb);

    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    then_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_bb);

    builder->setInsertBB(end_bb);
}

void IfElseStmt::genCode()
{
    // Todo
}

void CompoundStmt::genCode()
{
    // Todo
}

void SeqNode::genCode()
{
    // Todo
}

void DeclStmt::genCode()
{
    IdentifierSymbolEntry *se = dynamic_cast<IdentifierSymbolEntry *>(id->getSymPtr());
    if(se->isGlobal())
    {
        Operand *addr;
        SymbolEntry *addr_se;
        addr_se = new IdentifierSymbolEntry(*se);
        addr_se->setType(new PointerType(se->getType()));
        addr = new Operand(addr_se);
        se->setAddr(addr);
    }
    else if(se->isLocal())
    {
        Function *func = builder->getInsertBB()->getParent();
        BasicBlock *entry = func->getEntry();
        Instruction *alloca;
        Operand *addr;
        SymbolEntry *addr_se;
        Type *type;
        type = new PointerType(se->getType());
        addr_se = new TemporarySymbolEntry(type, SymbolTable::getLabel());
        addr = new Operand(addr_se);
        alloca = new AllocaInstruction(addr, se);                   // allocate space for local id in function stack.
        entry->insertFront(alloca);                                 // allocate instructions should be inserted into the begin of the entry block.
        se->setAddr(addr);                                          // set the addr operand in symbol entry so that we can use it in subsequent code generation.
    }
}

void ReturnStmt::genCode()
{
    // Todo
}

void AssignStmt::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    expr->genCode();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry*>(lval->getSymPtr())->getAddr();
    Operand *src = expr->getOperand();
    /***
     * We haven't implemented array yet, the lval can only be ID. So we just store the result of the `expr` to the addr of the id.
     * If you want to implement array, you have to caculate the address first and then store the result into it.
     */
    new StoreInstruction(addr, src, bb);
}

bool Ast::typeCheck(Type* retType)
{
    if(root != nullptr){
        root->typeCheck();
    }
}

bool ContinueStmt::typeCheck(Type* retType) {//参数可能用不到，但不写调用可能出错
    return false;
}

bool BreakStmt::typeCheck(Type* retType) {
    return false;
}

bool WhileStmt::typeCheck(Type* retType) {
    if (stmt != nullptr){
        bool res = stmt->typeCheck(retType);
        return res;
    }
    return false;
}

bool EmptyStmt::typeCheck(Type* retType) {
    return false;
}

bool FunctionCallExpr::typeCheck(Type* retType) {
    return false;
}
FunctionCallExpr::FunctionCallExpr(SymbolEntry* se, ExprNode* param = nullptr): ExprNode(se), param(param){
    // 创建函数调用节点时参数有可能不匹配，应该在构造时就发现错误
    SymbolEntry *tmp_se = se;
    long unsigned int count = 0;
    ExprNode *countNode = param;
    while(countNode != nullptr){
        countNode = (ExprNode*)(countNode->brother());
        ++count;
    }
    // 没有函数重载
    Type *type = tmp_se->getType();
    FunctionType *ft = (FunctionType *)type;
    std::vector<Type *> params = ft->getParamsType();
    if (count == params.size()){
        this->symbolEntry = tmp_se;
    }

    if (symbolEntry != nullptr){
        Type* type = symbolEntry->getType();
        FunctionType * ft2 = (FunctionType*)type;
        this->type = ft2->getRetType();
        if (this->type != TypeSystem::voidType){
            SymbolEntry* se = new TemporarySymbolEntry(this->type, SymbolTable::getLabel());
            dst = new Operand(se);
        }
        std::vector<Type*> params = ft2->getParamsType();
        ExprNode* temp = param;
        for (auto i = params.begin(); i != params.end(); ++i) {
            if (temp == nullptr) {
                fprintf(stderr, "too few arguments to function %s %s\n", symbolEntry->toStr().c_str(), type->toStr().c_str());
                break;
            } else if ((*i)->getKind() != temp->getType()->getKind()){
                fprintf(stderr, "parameter's type %s can't convert to %s\n", temp->getType()->toStr().c_str(), (*i)->toStr().c_str());
            }
            temp = (ExprNode*)(temp->brother());
        }
        // too many
        if (temp != nullptr) {
            fprintf(stderr, "too many arguments to function %s %s\n", symbolEntry->toStr().c_str(), type->toStr().c_str());
        }
    }

    if (((IdentifierSymbolEntry*)se)->isSysy() == true){
        unit.insertSysy(se);
    }

}

bool UnaryExpr::typeCheck(Type* retType) {
    return false;
}

UnaryExpr::UnaryExpr(SymbolEntry* se, int op, ExprNode* expr) : ExprNode(se, UNARYEXPR), op(op), expr(expr){
    std::string op_str;
    if (op == UnaryExpr::NOT){
        op_str = "!";
    }else{
        op_str = "-";
    }
    if (expr->getType()->isVoid()) {
        fprintf(stderr, "invalid operand of type \'void\' to unary \'opeartor%s\'\n", op_str.c_str());
    }

    if (op == UnaryExpr::NOT){
        type = TypeSystem::intType;
        dst = new Operand(se);
        if (expr->isUnaryExpr()) {
            UnaryExpr* ue = (UnaryExpr*)expr;
            if (ue->getOp() == UnaryExpr::NOT) {
                if (ue->getType() == TypeSystem::intType){
                    ue->setType(TypeSystem::boolType);
                }
            }
        }   
    } 
    else if (op == UnaryExpr::SUB) {
        type = TypeSystem::intType;
        dst = new Operand(se);
        if (expr->isUnaryExpr()) {
            UnaryExpr* ue = (UnaryExpr*)expr;
            if (ue->getOp() == UnaryExpr::NOT){
                if (ue->getType() == TypeSystem::intType){
                    ue->setType(TypeSystem::boolType);
                }
            }
        }
    }

}

bool ExprStmt::typeCheck(Type* retType) {
    return false;
}

bool FunctionDef::typeCheck(Type* retType)
{
    // Todo
    SymbolEntry* se = this->getSymbolEntry();
    StmtNode* stmt = this->stmt;
    FunctionType * ft = (FunctionType*)(se->getType());
    Type * funcRetType = ft->getRetType();
    if (!stmt){
        if (funcRetType != TypeSystem::voidType){
            fprintf(stderr, "non-void function does not return a value\n");
        }
        return false;
    }
    if (!stmt->typeCheck(funcRetType)) {// 返回值真假的作用是标识有没有遇到return语句
        fprintf(stderr, "function does not have a return statement\n");
        return false;
    }
    return false;
}

bool BinaryExpr::typeCheck(Type* retType = nullptr)
{
    return false;
}
ImplictCastExpr::ImplictCastExpr(ExprNode* expr): ExprNode(nullptr, IMPLICTCASTEXPR), expr(expr) {
    type = TypeSystem::boolType;
    dst = new Operand(new TemporarySymbolEntry(type, SymbolTable::getLabel()));
}
BinaryExpr::BinaryExpr(SymbolEntry* se, int op, ExprNode* expr1, ExprNode* expr2): ExprNode(se), op(op), expr1(expr1), expr2(expr2) {
    dst = new Operand(se);
    std::string op_str;
        switch (op) {
        case ADD:
            op_str = "+";
            break;
        case SUB:
            op_str = "-";
            break;
        case MUL:
            op_str = "*";
            break;
        case DIV:
            op_str = "/";
            break;
        case MOD:
            op_str = "%";
            break;
        case AND:
            op_str = "&&";
            break;
        case OR:
            op_str = "||";
            break;
        case LESS:
            op_str = "<";
            break;
        case LEQU:
            op_str = "<=";
            break;
        case GREAT:
            op_str = ">";
            break;
        case GEQU:
            op_str = ">=";
            break;
        case EQUAL:
            op_str = "==";
            break;
        case NOTEQUAL:
            op_str = "!=";
            break;
    }
    if (expr1->getType()->isVoid() || expr2->getType()->isVoid()) {
        fprintf(stderr, "invalid operand of type \'void\' to binary \'opeartor%s\'\n", op_str.c_str());
    }
    if ((op >= BinaryExpr::AND) && (op <= BinaryExpr::NOTEQUAL)) {
        type = TypeSystem::boolType;
        if (op == BinaryExpr::AND || op == BinaryExpr::OR) {
            if ((expr1->getType()->isInt()) && (expr1->getType()->getSize() == 32)) {
                ImplictCastExpr* ice = new ImplictCastExpr(expr1);
                this->expr1 = ice;
            }
            if ((expr2->getType()->isInt()) && (expr2->getType()->getSize() == 32)) {
                ImplictCastExpr* ice = new ImplictCastExpr(expr2);
                this->expr2 = ice;
            }
        }
    } 
    else{
        type = TypeSystem::intType;
    }
}

bool Constant::typeCheck(Type* retType = nullptr)
{
    return false;
}

bool Id::typeCheck(Type* retType = nullptr)
{
    return false;
}

bool IfStmt::typeCheck(Type* retType = nullptr)
{
    // Todo
    if (thenStmt != nullptr){
        bool res = thenStmt->typeCheck(retType);
        return res;
    }
    return false;
}

bool IfElseStmt::typeCheck(Type* retType = nullptr)
{
    // Todo
    bool res_then = false, res_else = false;
    if (thenStmt != nullptr){
        res_then = thenStmt->typeCheck(retType);
    }
    if (elseStmt != nullptr){
        res_else = elseStmt->typeCheck(retType);
    }
    return res_then || res_else;
}

bool CompoundStmt::typeCheck(Type* retType = nullptr)
{
    // Todo
    if (stmt != nullptr){
        bool res = stmt->typeCheck(retType);
        return res;
    }
    return false;
}

bool SeqNode::typeCheck(Type* retType = nullptr)
{
    // Todo
    bool res_stmt1 = false, res_stmt2 = false;
    if (stmt1 != nullptr){
        res_stmt1 = stmt1->typeCheck(retType);
    }
    if (stmt2 != nullptr){
        res_stmt2 = stmt2->typeCheck(retType);
    }
    return res_stmt1 || res_stmt2;
}

bool DeclStmt::typeCheck(Type* retType = nullptr)
{
    return false;
}

bool ReturnStmt::typeCheck(Type* retType = nullptr)
{
    // 如果在函数定义外
    if (retType == nullptr) {
        fprintf(stderr, "expected unqualified-id\n");
        return true;
    }
    if ((retValue == nullptr) && (retType->isVoid() == false)){
        fprintf(stderr, "return-statement with no value, in function returning \"%s\"\n",retType->toStr().c_str());
        return true;
    }
    if ((retType != nullptr) && (retType->isVoid() == true)){
        fprintf(stderr, "return-statement with a value, in function returning \"%s\"\n",retType->toStr().c_str());
        return true;
    }
    Type* type = retValue->getType();
    if (type != retType) {
        fprintf(stderr, "cannot initialize return object of type \"%s\" with an rvalue of type \"%s\"\n",
                retType->toStr().c_str(), type->toStr().c_str());
        return true;
    }
    return true;
}

bool AssignStmt::typeCheck(Type* retType = nullptr)
{
    return false;
}
AssignStmt::AssignStmt(ExprNode* lval, ExprNode* expr): lval(lval), expr(expr) {
    Type* type = ((Id*)lval)->getType();
    SymbolEntry* se = lval->getSymbolEntry();

    if (type->isInt()){
        if (((IntType*)type)->isConstant()) {
            fprintf(stderr, "cannot assign to variable \'%s\' with const-qualified type \'%s\'\n", ((IdentifierSymbolEntry*)se)->toStr().c_str(), type->toStr().c_str());
        }
    }
    if ((expr->getType()->isInt()) == false){
        fprintf(stderr, "cannot initialize a variable of type \'int\' with an rvalue of type \'%s\'\n", expr->getType()->toStr().c_str());
    }

}

void ImplictCastExpr::output(int level) {
    fprintf(yyout, "%*cImplictCastExpr\ttype: %s to %s\n", level, ' ', expr->getType()->toStr().c_str(), type->toStr().c_str());
    this->expr->output(level + 4);
}

void BinaryExpr::output(int level)
{
    std::string op_str;
    switch(op)
    {
        case ADD:
            op_str = "add";
            break;
        case SUB:
            op_str = "sub";
            break;
        case MUL:
            op_str = "mul";
            break;
        case DIV:
            op_str = "div";
            break;
        case MOD:
            op_str = "mod";
            break;
        case AND:
            op_str = "and";
            break;
        case OR:
            op_str = "or";
            break;
        case LESS:
            op_str = "less";
            break;
        case LEQU:
            op_str = "lequ";
            break;
        case EQUAL:
            op_str = "equal";
            break;
        case NOTEQUAL:
            op_str = "notequal";
            break;
        case GREAT:
            op_str = "great";
            break;
        case GEQU:
            op_str = "gequ";
            break;
    }
    fprintf(yyout, "%*cBinaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr1->output(level + 4);
    expr2->output(level + 4);
}

void UnaryExpr::output(int level) 
{
    std::string op_str;
    switch (op) {
        case NOT:
            op_str = "not";
            break;
        case SUB:
            op_str = "negative";
            break;
    }
    fprintf(yyout, "%*cUnaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr->output(level + 4);
}

// TODO: FunctionCall
void FunctionCallExpr::output(int level) {
    std::string name, type;
    int scope;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    scope = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getScope();
    fprintf(yyout, "%*cCallee\tfunction name: %s\ttype: %s\tscope:  %d\n",
            level, ' ', name.c_str(), type.c_str(), scope);
    Node* tmp = param;
    while (tmp) {
        tmp->output(level + 4);
        tmp = tmp->brother();
    }
}

void Ast::output()
{
    fprintf(yyout, "program\n");
    if(root != nullptr)
        root->output(4);
}

void Constant::output(int level)
{
    std::string type, value;
    type = symbolEntry->getType()->toStr();
    value = symbolEntry->toStr();
    fprintf(yyout, "%*cIntegerLiteral\tvalue: %s\ttype: %s\n", level, ' ',
            value.c_str(), type.c_str());
}

void Id::output(int level)
{
    std::string name, type;
    int scope;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    scope = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getScope();
    fprintf(yyout, "%*cId\tname: %s\tscope: %d\ttype: %s\n", level, ' ',
            name.c_str(), scope, type.c_str());
}

void CompoundStmt::output(int level)
{
    fprintf(yyout, "%*cCompoundStmt\n", level, ' ');
    stmt->output(level + 4);
}

void SeqNode::output(int level)
{
    stmt1->output(level);
    stmt2->output(level);
}

void DeclStmt::output(int level)
{
    fprintf(yyout, "%*cDeclStmt\n", level, ' ');
    id->output(level + 4);
    if (expr) expr->output(level + 4);
    if (this->brother()) this->brother()->output(level);
}

void IfStmt::output(int level)
{
    fprintf(yyout, "%*cIfStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
}

void IfElseStmt::output(int level)
{
    fprintf(yyout, "%*cIfElseStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
    elseStmt->output(level + 4);
}

void WhileStmt::output(int level) 
{
    fprintf(yyout, "%*cWhileStmt\n", level, ' ');
    cond->output(level + 4);
    stmt->output(level + 4);
}

void BreakStmt::output(int level)
 {
    fprintf(yyout, "%*cBreakStmt\n", level, ' ');
}

void ContinueStmt::output(int level) 
{
    fprintf(yyout, "%*cContinueStmt\n", level, ' ');
}

void ReturnStmt::output(int level)
{
    fprintf(yyout, "%*cReturnStmt\n", level, ' ');
    retValue->output(level + 4);
}

void AssignStmt::output(int level)
{
    fprintf(yyout, "%*cAssignStmt\n", level, ' ');
    lval->output(level + 4);
    expr->output(level + 4);
}

void ExprStmt::output(int level)
{
    fprintf(yyout, "%*cAssignStmt\n", level, ' ');
    expr->output(level + 4);
}

void EmptyStmt::output(int level)
{
    fprintf(yyout, "%*cEmptyStmt\n", level, ' ');
}


void FunctionDef::output(int level)
{
    std::string name, type;
    name = se->toStr();
    type = se->getType()->toStr();
    fprintf(yyout, "%*cFunctionDefine function name: %s, type: %s\n", level, ' ', 
            name.c_str(), type.c_str());
    stmt->output(level + 4);
}
